apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-node-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-node-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-taint-label
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["taint", "label", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-get-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-create
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-controller-node-taint-label-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-taint-label
subjects:
- kind: ServiceAccount
  name: canary-node-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-controller-pod-get-list-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-get-list
subjects:
- kind: ServiceAccount
  name: canary-node-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: canary-operator-node-taint-label-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-taint-label
subjects:
- kind: ServiceAccount
  name: canary-node-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-operator-pod-get-list-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-get-list
subjects:
- kind: ServiceAccount
  name: canary-node-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-operator-pod-create-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-create
subjects:
- kind: ServiceAccount
  name: canary-node-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-operator
  template:
    metadata:
      labels:
        app: canary-operator
    spec:
      serviceAccountName: canary-node-operator
      containers:
      - name: canary-operator
        image: ghcr.io/markjgardner/aks-disable-win-av-updates/winnodeoperator:0.4
        env:
        - name: CONTROLLER_SERVICE_ACCOUNT
          value: canary-node-controller
        - name: CONTROLLER_IMAGE
          value: ghcr.io/markjgardner/aks-disable-win-av-updates/nodecontroller:0.2.91
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 250Mi