apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disable-windowsav
  labels:
    k8s-app: disable-windowsav
spec:
  selector:
    matchLabels:
      name: disable-windowsav
  template:
    metadata:
      labels:
        name: disable-windowsav
    spec:
      nodeSelector:
        kubernetes.azure.com/os-sku: Windows2022
      hostNetwork: true
      initContainers:
      - name: disable-windowsav
        image: mcr.microsoft.com/windows/nanoserver:ltsc2022
        command:
        - powershell.exe
        args:
        - -Command
        - |
          reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates' /v SignatureUpdateInterval /t REG_DWORD /d 0 /f;
          reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates' /v SignaturesUpdatesChannel /t REG_SZ /d 'staged' /f;
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"
      containers:
      - name: log-regkeys
        image: mcr.microsoft.com/windows/nanoserver:ltsc2022
        command:
        - powershell.exe
        args:
        - -Command
        - while ($true) { reg query 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Signature Updates'; start-sleep -s 600; }
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"