apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-node-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-taint-label
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["taint", "label", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-node-taint-label-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-taint-label
subjects:
- kind: ServiceAccount
  name: canary-node-controller
---
apiVersion: node.winops/v1alpha1
kind: Canary
metadata:
  labels:
    app.kubernetes.io/name: canary
    app.kubernetes.io/instance: canary-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: canary-sample
spec:
  serviceAccountName: canary-node-controller